export {default as Home} from './Home'
export {default as Register} from './Register'
export {default as EmailConfirm} from './EmailConfrim'
export {default as Dashboard} from './Dashboard'
export {default as InventoryForm} from './InventoryForm'